const constants = {
    ADD_CART_PRODUCT: 'ADD_CART_PRODUCT',
    SET_PRODUCT_QUANTITY: 'SET_PRODUCT_QUANTITY',
    REMOVE_CART_PRODUCT: 'REMOVE_CART_PRODUCT',
    CLEAR_CART_PRODUCTS: 'CLEAR_CART_PRODUCTS'
};

export default constants;